package org.ciudadesAbiertas.madrid.model.dynamic;
// Generated 22-jun-2017 10:58:01 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;



/**
 * UrlGroup generated by hbm2java
 */
@Entity
@Table(name = "url_group")
public class UrlGroup implements java.io.Serializable {

	private String code;
	

	public UrlGroup() {
	}

	public UrlGroup(String code) {
		this.code = code;
	}


	@Id
	@Column(name = "code", unique = true, nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
