  select
        alfa,
        bravo,
        charlie,
        delta,
        echo,
        foxtrot,
        golf,
        hotel,
        india,
        juliet,
        november,
        oscar,
        papa,
        quebec,
        romeo,
        tango,
        uniform,
        victor,
        whiskey      
    from
        test_table