package com.localidata.htools;
// Generated 17 ene. 2020 13:22:36 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EntidadBase generated by hbm2java
 */
@Entity
@Table(name = "entidad_base", catalog = "baseMadrid")
public class EntidadBase implements java.io.Serializable {

	private String id;
	private String texto;
	private String textoLargo;
	private Date fecha;
	private int numeroEntero;
	private BigDecimal numeroDecimal;

	public EntidadBase() {
	}

	public EntidadBase(String id, String texto, String textoLargo, Date fecha, int numeroEntero,
			BigDecimal numeroDecimal) {
		this.id = id;
		this.texto = texto;
		this.textoLargo = textoLargo;
		this.fecha = fecha;
		this.numeroEntero = numeroEntero;
		this.numeroDecimal = numeroDecimal;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "texto", nullable = false, length = 100)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "texto_largo", nullable = false, length = 4000)
	public String getTextoLargo() {
		return this.textoLargo;
	}

	public void setTextoLargo(String textoLargo) {
		this.textoLargo = textoLargo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "numero_entero", nullable = false)
	public int getNumeroEntero() {
		return this.numeroEntero;
	}

	public void setNumeroEntero(int numeroEntero) {
		this.numeroEntero = numeroEntero;
	}

	@Column(name = "numero_decimal", nullable = false, precision = 12)
	public BigDecimal getNumeroDecimal() {
		return this.numeroDecimal;
	}

	public void setNumeroDecimal(BigDecimal numeroDecimal) {
		this.numeroDecimal = numeroDecimal;
	}

}
