package com.localidata.htools;
// Generated 17 ene. 2020 13:22:36 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Estadistica generated by hbm2java
 */
@Entity
@Table(name = "estadistica", catalog = "baseMadrid")
public class Estadistica implements java.io.Serializable {

	private String id;
	private String usuario;
	private String url;
	private Date fechaPeticion;
	private String origen;
	private String userAgent;

	public Estadistica() {
	}

	public Estadistica(String id, String usuario, String url, Date fechaPeticion, String origen, String userAgent) {
		this.id = id;
		this.usuario = usuario;
		this.url = url;
		this.fechaPeticion = fechaPeticion;
		this.origen = origen;
		this.userAgent = userAgent;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "usuario", nullable = false, length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "url", nullable = false, length = 2000)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_peticion", nullable = false, length = 19)
	public Date getFechaPeticion() {
		return this.fechaPeticion;
	}

	public void setFechaPeticion(Date fechaPeticion) {
		this.fechaPeticion = fechaPeticion;
	}

	@Column(name = "origen", nullable = false, length = 20)
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	@Column(name = "user_agent", nullable = false, length = 200)
	public String getUserAgent() {
		return this.userAgent;
	}

	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}

}
