package com.localidata.htools;
// Generated 17 ene. 2020 13:22:36 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OauthCode generated by hbm2java
 */
@Entity
@Table(name = "oauth_code", catalog = "baseMadrid")
public class OauthCode implements java.io.Serializable {

	private OauthCodeId id;

	public OauthCode() {
	}

	public OauthCode(OauthCodeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "code", column = @Column(name = "code")),
			@AttributeOverride(name = "authentication", column = @Column(name = "authentication")) })
	public OauthCodeId getId() {
		return this.id;
	}

	public void setId(OauthCodeId id) {
		this.id = id;
	}

}
