package com.localidata.htools;
// Generated 17 ene. 2020 13:22:36 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name = "ciudad", catalog = "baseMadrid")
public class Ciudad implements java.io.Serializable {

	private String id;
	private String nombre;

	public Ciudad() {
	}

	public Ciudad(String id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
