package com.localidata.htools;
// Generated 1 jul. 2020 14:16:07 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Equipamiento generated by hbm2java
 */
@Entity
@Table(name = "equipamiento", catalog = "apiDinamica")
public class Equipamiento implements java.io.Serializable {

    private String ikey;
    private String id;
    private String title;
    private String description;
    private String tipoEquipamiento;
    private String paisId;
    private String provinciaId;
    private String autonomiaId;
    private String distritoId;
    private String barrioId;
    private String municipioId;
    private String municipioTitle;
    private String streetAddress;
    private String postalCode;
    private BigDecimal XEtrs89;
    private BigDecimal YEtrs89;
    private String email;
    private String telephone;
    private String url;
    private Boolean titularidadPublica;
    private String openingHours;

    public Equipamiento() {
    }

    public Equipamiento(String ikey) {
	this.ikey = ikey;
    }

    public Equipamiento(String ikey, String id, String title, String description, String tipoEquipamiento, String paisId, String provinciaId, String autonomiaId, String distritoId, String barrioId, String municipioId, String municipioTitle,
	    String streetAddress, String postalCode, BigDecimal XEtrs89, BigDecimal YEtrs89, String email, String telephone, String url, Boolean titularidadPublica, String openingHours) {
	this.ikey = ikey;
	this.id = id;
	this.title = title;
	this.description = description;
	this.tipoEquipamiento = tipoEquipamiento;
	this.paisId = paisId;
	this.provinciaId = provinciaId;
	this.autonomiaId = autonomiaId;
	this.distritoId = distritoId;
	this.barrioId = barrioId;
	this.municipioId = municipioId;
	this.municipioTitle = municipioTitle;
	this.streetAddress = streetAddress;
	this.postalCode = postalCode;
	this.XEtrs89 = XEtrs89;
	this.YEtrs89 = YEtrs89;
	this.email = email;
	this.telephone = telephone;
	this.url = url;
	this.titularidadPublica = titularidadPublica;
	this.openingHours = openingHours;
    }

    @Id

    @Column(name = "ikey", unique = true, nullable = false, length = 50)
    public String getIkey() {
	return this.ikey;
    }

    public void setIkey(String ikey) {
	this.ikey = ikey;
    }

    @Column(name = "id", length = 50)
    public String getId() {
	return this.id;
    }

    public void setId(String id) {
	this.id = id;
    }

    @Column(name = "title", length = 400)
    public String getTitle() {
	return this.title;
    }

    public void setTitle(String title) {
	this.title = title;
    }

    @Column(name = "description", length = 4000)
    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

    @Column(name = "tipo_equipamiento", length = 100)
    public String getTipoEquipamiento() {
	return this.tipoEquipamiento;
    }

    public void setTipoEquipamiento(String tipoEquipamiento) {
	this.tipoEquipamiento = tipoEquipamiento;
    }

    @Column(name = "pais_id", length = 50)
    public String getPaisId() {
	return this.paisId;
    }

    public void setPaisId(String paisId) {
	this.paisId = paisId;
    }

    @Column(name = "provincia_id", length = 50)
    public String getProvinciaId() {
	return this.provinciaId;
    }

    public void setProvinciaId(String provinciaId) {
	this.provinciaId = provinciaId;
    }

    @Column(name = "autonomia_id", length = 50)
    public String getAutonomiaId() {
	return this.autonomiaId;
    }

    public void setAutonomiaId(String autonomiaId) {
	this.autonomiaId = autonomiaId;
    }

    @Column(name = "distrito_id", length = 200)
    public String getDistritoId() {
	return this.distritoId;
    }

    public void setDistritoId(String distritoId) {
	this.distritoId = distritoId;
    }

    @Column(name = "barrio_id", length = 50)
    public String getBarrioId() {
	return this.barrioId;
    }

    public void setBarrioId(String barrioId) {
	this.barrioId = barrioId;
    }

    @Column(name = "municipio_id", length = 510)
    public String getMunicipioId() {
	return this.municipioId;
    }

    public void setMunicipioId(String municipioId) {
	this.municipioId = municipioId;
    }

    @Column(name = "municipio_title", length = 200)
    public String getMunicipioTitle() {
	return this.municipioTitle;
    }

    public void setMunicipioTitle(String municipioTitle) {
	this.municipioTitle = municipioTitle;
    }

    @Column(name = "street_address", length = 200)
    public String getStreetAddress() {
	return this.streetAddress;
    }

    public void setStreetAddress(String streetAddress) {
	this.streetAddress = streetAddress;
    }

    @Column(name = "postal_code", length = 10)
    public String getPostalCode() {
	return this.postalCode;
    }

    public void setPostalCode(String postalCode) {
	this.postalCode = postalCode;
    }

    @Column(name = "x_etrs89", precision = 13, scale = 5)
    public BigDecimal getXEtrs89() {
	return this.XEtrs89;
    }

    public void setXEtrs89(BigDecimal XEtrs89) {
	this.XEtrs89 = XEtrs89;
    }

    @Column(name = "y_etrs89", precision = 13, scale = 5)
    public BigDecimal getYEtrs89() {
	return this.YEtrs89;
    }

    public void setYEtrs89(BigDecimal YEtrs89) {
	this.YEtrs89 = YEtrs89;
    }

    @Column(name = "email", length = 200)
    public String getEmail() {
	return this.email;
    }

    public void setEmail(String email) {
	this.email = email;
    }

    @Column(name = "telephone", length = 200)
    public String getTelephone() {
	return this.telephone;
    }

    public void setTelephone(String telephone) {
	this.telephone = telephone;
    }

    @Column(name = "url", length = 400)
    public String getUrl() {
	return this.url;
    }

    public void setUrl(String url) {
	this.url = url;
    }

    @Column(name = "titularidad_publica")
    public Boolean getTitularidadPublica() {
	return this.titularidadPublica;
    }

    public void setTitularidadPublica(Boolean titularidadPublica) {
	this.titularidadPublica = titularidadPublica;
    }

    @Column(name = "opening_hours", length = 400)
    public String getOpeningHours() {
	return this.openingHours;
    }

    public void setOpeningHours(String openingHours) {
	this.openingHours = openingHours;
    }

}
