package com.localidata.htools;
// Generated 19 ene. 2021 10:56:41 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name = "groups", catalog = "apiDinamica")
public class Groups implements java.io.Serializable {

private long id;
private String groupName;
private Set<GroupMembers> groupMemberses = new HashSet<GroupMembers>(0);
private GroupAuthorities groupAuthorities;

public Groups() {
}

public Groups(long id, String groupName) {
  this.id = id;
  this.groupName = groupName;
}

public Groups(long id, String groupName, Set<GroupMembers> groupMemberses, GroupAuthorities groupAuthorities) {
  this.id = id;
  this.groupName = groupName;
  this.groupMemberses = groupMemberses;
  this.groupAuthorities = groupAuthorities;
}

@Id

@Column(name = "id", unique = true, nullable = false)
public long getId() {
  return this.id;
}

public void setId(long id) {
  this.id = id;
}

@Column(name = "group_name", nullable = false, length = 50)
public String getGroupName() {
  return this.groupName;
}

public void setGroupName(String groupName) {
  this.groupName = groupName;
}

@OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
public Set<GroupMembers> getGroupMemberses() {
  return this.groupMemberses;
}

public void setGroupMemberses(Set<GroupMembers> groupMemberses) {
  this.groupMemberses = groupMemberses;
}

@OneToOne(fetch = FetchType.LAZY, mappedBy = "groups")
public GroupAuthorities getGroupAuthorities() {
  return this.groupAuthorities;
}

public void setGroupAuthorities(GroupAuthorities groupAuthorities) {
  this.groupAuthorities = groupAuthorities;
}

}
