package com.localidata.htools;
// Generated 19 ene. 2021 10:56:41 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Query generated by hbm2java
 */
@Entity
@Table(name = "query", catalog = "apiDinamica", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Query implements java.io.Serializable {

private int id;
private String code;
private String texto;
private String databaseCon;
private String summary;
private String tags;
private String definition;
private Set<SemanticRelPrefix> semanticRelPrefixes = new HashSet<SemanticRelPrefix>(0);
private Set<Param> params = new HashSet<Param>(0);
private Set<SemanticRml> semanticRmls = new HashSet<SemanticRml>(0);
private Set<SemanticField> semanticFields = new HashSet<SemanticField>(0);

public Query() {
}

public Query(int id, String code, String texto, String databaseCon, String tags) {
  this.id = id;
  this.code = code;
  this.texto = texto;
  this.databaseCon = databaseCon;
  this.tags = tags;
}

public Query(int id, String code, String texto, String databaseCon, String summary, String tags, String definition, Set<SemanticRelPrefix> semanticRelPrefixes, Set<Param> params, Set<SemanticRml> semanticRmls,
	Set<SemanticField> semanticFields) {
  this.id = id;
  this.code = code;
  this.texto = texto;
  this.databaseCon = databaseCon;
  this.summary = summary;
  this.tags = tags;
  this.definition = definition;
  this.semanticRelPrefixes = semanticRelPrefixes;
  this.params = params;
  this.semanticRmls = semanticRmls;
  this.semanticFields = semanticFields;
}

@Id

@Column(name = "id", unique = true, nullable = false)
public int getId() {
  return this.id;
}

public void setId(int id) {
  this.id = id;
}

@Column(name = "code", unique = true, nullable = false, length = 50)
public String getCode() {
  return this.code;
}

public void setCode(String code) {
  this.code = code;
}

@Column(name = "texto", nullable = false, length = 4000)
public String getTexto() {
  return this.texto;
}

public void setTexto(String texto) {
  this.texto = texto;
}

@Column(name = "database_con", nullable = false, length = 20)
public String getDatabaseCon() {
  return this.databaseCon;
}

public void setDatabaseCon(String databaseCon) {
  this.databaseCon = databaseCon;
}

@Column(name = "summary", length = 100)
public String getSummary() {
  return this.summary;
}

public void setSummary(String summary) {
  this.summary = summary;
}

@Column(name = "tags", nullable = false)
public String getTags() {
  return this.tags;
}

public void setTags(String tags) {
  this.tags = tags;
}

@Column(name = "definition", length = 100)
public String getDefinition() {
  return this.definition;
}

public void setDefinition(String definition) {
  this.definition = definition;
}

@OneToMany(fetch = FetchType.LAZY, mappedBy = "query")
public Set<SemanticRelPrefix> getSemanticRelPrefixes() {
  return this.semanticRelPrefixes;
}

public void setSemanticRelPrefixes(Set<SemanticRelPrefix> semanticRelPrefixes) {
  this.semanticRelPrefixes = semanticRelPrefixes;
}

@OneToMany(fetch = FetchType.LAZY, mappedBy = "query")
public Set<Param> getParams() {
  return this.params;
}

public void setParams(Set<Param> params) {
  this.params = params;
}

@OneToMany(fetch = FetchType.LAZY, mappedBy = "query")
public Set<SemanticRml> getSemanticRmls() {
  return this.semanticRmls;
}

public void setSemanticRmls(Set<SemanticRml> semanticRmls) {
  this.semanticRmls = semanticRmls;
}

@OneToMany(fetch = FetchType.LAZY, mappedBy = "query")
public Set<SemanticField> getSemanticFields() {
  return this.semanticFields;
}

public void setSemanticFields(Set<SemanticField> semanticFields) {
  this.semanticFields = semanticFields;
}

}
