package com.localidata.htools;
// Generated 1 jul. 2020 14:16:07 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SemanticField generated by hbm2java
 */
@Entity
@Table(name = "semantic_field", catalog = "apiDinamica")
public class SemanticField implements java.io.Serializable {

    private String id;
    private Query query;
    private String field;
    private String predicate;
    private String objectReference;
    private String objectType;
    private boolean objectUri;

    public SemanticField() {
    }

    public SemanticField(String id, Query query, String field, String predicate, String objectReference, String objectType, boolean objectUri) {
	this.id = id;
	this.query = query;
	this.field = field;
	this.predicate = predicate;
	this.objectReference = objectReference;
	this.objectType = objectType;
	this.objectUri = objectUri;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false, length = 50)
    public String getId() {
	return this.id;
    }

    public void setId(String id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "query", nullable = false)
    public Query getQuery() {
	return this.query;
    }

    public void setQuery(Query query) {
	this.query = query;
    }

    @Column(name = "field", nullable = false, length = 100)
    public String getField() {
	return this.field;
    }

    public void setField(String field) {
	this.field = field;
    }

    @Column(name = "predicate", nullable = false, length = 200)
    public String getPredicate() {
	return this.predicate;
    }

    public void setPredicate(String predicate) {
	this.predicate = predicate;
    }

    @Column(name = "object_reference", nullable = false, length = 200)
    public String getObjectReference() {
	return this.objectReference;
    }

    public void setObjectReference(String objectReference) {
	this.objectReference = objectReference;
    }

    @Column(name = "object_type", nullable = false, length = 50)
    public String getObjectType() {
	return this.objectType;
    }

    public void setObjectType(String objectType) {
	this.objectType = objectType;
    }

    @Column(name = "object_uri", nullable = false)
    public boolean isObjectUri() {
	return this.objectUri;
    }

    public void setObjectUri(boolean objectUri) {
	this.objectUri = objectUri;
    }

}
