package com.localidata.htools;
// Generated 19 ene. 2021 10:56:41 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subvencion generated by hbm2java
 */
@Entity
@Table(name = "subvencion", catalog = "apiDinamica")
public class Subvencion implements java.io.Serializable {

private String ikey;
private String id;
private String title;
private String areaId;
private String areaTitle;
private String municipioId;
private String municipioTitle;
private String adjudicatarioId;
private String adjudicatarioTitle;
private String entidadFinanciadoraId;
private String entidadFinanciadoraTitle;
private BigDecimal importe;
private Date fechaAdjudicacion;
private String lineaFinanciacion;
private String basesReguladoras;
private String tipoInstrumento;
private String aplicacionPresupuestaria;
private Boolean nominativa;
private String tipoProcedimiento;

public Subvencion() {
}

public Subvencion(String ikey) {
  this.ikey = ikey;
}

public Subvencion(String ikey, String id, String title, String areaId, String areaTitle, String municipioId, String municipioTitle, String adjudicatarioId, String adjudicatarioTitle, String entidadFinanciadoraId,
	String entidadFinanciadoraTitle, BigDecimal importe, Date fechaAdjudicacion, String lineaFinanciacion, String basesReguladoras, String tipoInstrumento, String aplicacionPresupuestaria, Boolean nominativa, String tipoProcedimiento) {
  this.ikey = ikey;
  this.id = id;
  this.title = title;
  this.areaId = areaId;
  this.areaTitle = areaTitle;
  this.municipioId = municipioId;
  this.municipioTitle = municipioTitle;
  this.adjudicatarioId = adjudicatarioId;
  this.adjudicatarioTitle = adjudicatarioTitle;
  this.entidadFinanciadoraId = entidadFinanciadoraId;
  this.entidadFinanciadoraTitle = entidadFinanciadoraTitle;
  this.importe = importe;
  this.fechaAdjudicacion = fechaAdjudicacion;
  this.lineaFinanciacion = lineaFinanciacion;
  this.basesReguladoras = basesReguladoras;
  this.tipoInstrumento = tipoInstrumento;
  this.aplicacionPresupuestaria = aplicacionPresupuestaria;
  this.nominativa = nominativa;
  this.tipoProcedimiento = tipoProcedimiento;
}

@Id

@Column(name = "ikey", unique = true, nullable = false, length = 50)
public String getIkey() {
  return this.ikey;
}

public void setIkey(String ikey) {
  this.ikey = ikey;
}

@Column(name = "id", length = 50)
public String getId() {
  return this.id;
}

public void setId(String id) {
  this.id = id;
}

@Column(name = "title", length = 400)
public String getTitle() {
  return this.title;
}

public void setTitle(String title) {
  this.title = title;
}

@Column(name = "area_id", length = 50)
public String getAreaId() {
  return this.areaId;
}

public void setAreaId(String areaId) {
  this.areaId = areaId;
}

@Column(name = "area_title", length = 200)
public String getAreaTitle() {
  return this.areaTitle;
}

public void setAreaTitle(String areaTitle) {
  this.areaTitle = areaTitle;
}

@Column(name = "municipio_id", length = 50)
public String getMunicipioId() {
  return this.municipioId;
}

public void setMunicipioId(String municipioId) {
  this.municipioId = municipioId;
}

@Column(name = "municipio_title", length = 200)
public String getMunicipioTitle() {
  return this.municipioTitle;
}

public void setMunicipioTitle(String municipioTitle) {
  this.municipioTitle = municipioTitle;
}

@Column(name = "adjudicatario_id", length = 50)
public String getAdjudicatarioId() {
  return this.adjudicatarioId;
}

public void setAdjudicatarioId(String adjudicatarioId) {
  this.adjudicatarioId = adjudicatarioId;
}

@Column(name = "adjudicatario_title", length = 200)
public String getAdjudicatarioTitle() {
  return this.adjudicatarioTitle;
}

public void setAdjudicatarioTitle(String adjudicatarioTitle) {
  this.adjudicatarioTitle = adjudicatarioTitle;
}

@Column(name = "entidad_financiadora_id", length = 50)
public String getEntidadFinanciadoraId() {
  return this.entidadFinanciadoraId;
}

public void setEntidadFinanciadoraId(String entidadFinanciadoraId) {
  this.entidadFinanciadoraId = entidadFinanciadoraId;
}

@Column(name = "entidad_financiadora_title", length = 200)
public String getEntidadFinanciadoraTitle() {
  return this.entidadFinanciadoraTitle;
}

public void setEntidadFinanciadoraTitle(String entidadFinanciadoraTitle) {
  this.entidadFinanciadoraTitle = entidadFinanciadoraTitle;
}

@Column(name = "importe", precision = 12)
public BigDecimal getImporte() {
  return this.importe;
}

public void setImporte(BigDecimal importe) {
  this.importe = importe;
}

@Temporal(TemporalType.TIMESTAMP)
@Column(name = "fecha_adjudicacion", length = 19)
public Date getFechaAdjudicacion() {
  return this.fechaAdjudicacion;
}

public void setFechaAdjudicacion(Date fechaAdjudicacion) {
  this.fechaAdjudicacion = fechaAdjudicacion;
}

@Column(name = "linea_financiacion", length = 200)
public String getLineaFinanciacion() {
  return this.lineaFinanciacion;
}

public void setLineaFinanciacion(String lineaFinanciacion) {
  this.lineaFinanciacion = lineaFinanciacion;
}

@Column(name = "bases_reguladoras", length = 400)
public String getBasesReguladoras() {
  return this.basesReguladoras;
}

public void setBasesReguladoras(String basesReguladoras) {
  this.basesReguladoras = basesReguladoras;
}

@Column(name = "tipo_instrumento", length = 100)
public String getTipoInstrumento() {
  return this.tipoInstrumento;
}

public void setTipoInstrumento(String tipoInstrumento) {
  this.tipoInstrumento = tipoInstrumento;
}

@Column(name = "aplicacion_presupuestaria", length = 100)
public String getAplicacionPresupuestaria() {
  return this.aplicacionPresupuestaria;
}

public void setAplicacionPresupuestaria(String aplicacionPresupuestaria) {
  this.aplicacionPresupuestaria = aplicacionPresupuestaria;
}

@Column(name = "nominativa")
public Boolean getNominativa() {
  return this.nominativa;
}

public void setNominativa(Boolean nominativa) {
  this.nominativa = nominativa;
}

@Column(name = "tipo_procedimiento", length = 100)
public String getTipoProcedimiento() {
  return this.tipoProcedimiento;
}

public void setTipoProcedimiento(String tipoProcedimiento) {
  this.tipoProcedimiento = tipoProcedimiento;
}

}
