package com.localidata.htools;
// Generated 19 ene. 2021 10:56:41 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SwaggerDefinition generated by hbm2java
 */
@Entity
@Table(name = "swagger_definition", catalog = "apiDinamica")
public class SwaggerDefinition implements java.io.Serializable {

private SwaggerDefinitionId id;

public SwaggerDefinition() {
}

public SwaggerDefinition(SwaggerDefinitionId id) {
  this.id = id;
}

@EmbeddedId

@AttributeOverrides({ @AttributeOverride(name = "code", column = @Column(name = "code", nullable = false, length = 100)), @AttributeOverride(name = "description", column = @Column(name = "description", nullable = false, length = 200)),
	@AttributeOverride(name = "text", column = @Column(name = "text", nullable = false, length = 4000)) })
public SwaggerDefinitionId getId() {
  return this.id;
}

public void setId(SwaggerDefinitionId id) {
  this.id = id;
}

}
