package com.localidata.htools;
// Generated 1 jul. 2020 14:16:07 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TerritorioPais generated by hbm2java
 */
@Entity
@Table(name = "territorio_pais", catalog = "apiDinamica")
public class TerritorioPais implements java.io.Serializable {

    private String ikey;
    private String id;
    private String identifier;
    private String title;
    private String geometry;

    public TerritorioPais() {
    }

    public TerritorioPais(String ikey, String id, String identifier, String title) {
	this.ikey = ikey;
	this.id = id;
	this.identifier = identifier;
	this.title = title;
    }

    public TerritorioPais(String ikey, String id, String identifier, String title, String geometry) {
	this.ikey = ikey;
	this.id = id;
	this.identifier = identifier;
	this.title = title;
	this.geometry = geometry;
    }

    @Id

    @Column(name = "ikey", unique = true, nullable = false, length = 50)
    public String getIkey() {
	return this.ikey;
    }

    public void setIkey(String ikey) {
	this.ikey = ikey;
    }

    @Column(name = "id", nullable = false, length = 50)
    public String getId() {
	return this.id;
    }

    public void setId(String id) {
	this.id = id;
    }

    @Column(name = "identifier", nullable = false, length = 400)
    public String getIdentifier() {
	return this.identifier;
    }

    public void setIdentifier(String identifier) {
	this.identifier = identifier;
    }

    @Column(name = "title", nullable = false, length = 400)
    public String getTitle() {
	return this.title;
    }

    public void setTitle(String title) {
	this.title = title;
    }

    @Column(name = "geometry")
    public String getGeometry() {
	return this.geometry;
    }

    public void setGeometry(String geometry) {
	this.geometry = geometry;
    }

}
